### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by n-katou** [n-katou/ViMemo#27]
### 実装予定の機能
- [ ] ユーザー関連
 - ユーザー登録
 - ユーザー編集
 - ユーザー権限付与
 - ログイン/ログアウト機能
 - パスワードリセット機能
 - 退会機能
- [ ] Google認証ログイン機能
- [ ] メモ関連
 - メモ投稿
 - メモ編集
 - メモ削除
 - 検索機能
 - いいね機能
- [ ] Xでシェア機能
- [ ] 投稿動画関連
 - 動画投稿
 - 動画編集
 - 動画削除
 - 検索機能
 - いいね機能
- [ ] youtube動画取得機能
- [ ] youtube一覧と投稿動画一覧の切り替え機能

**Comment by tarakish** [comment]
Projectsにアクセスしましたが、カンバン・issue・ストーリーポイントが確認できませんでした。
カリキュラムをご確認の上、上記が確認できる状態でご提出をお願いいたします。
![スクリーンショット 2024-03-31 14 35 43](https://github.com/n-katou/ViMemo/assets/71510236/fc4d8a18-c7c9-47ba-9036-0b9e68b92038)

**Comment by n-katou** [comment]
失礼しました。
publicに変更しましたので、ご確認をよろしくお願いいたします。

**Comment by kenchasonakai** [comment]
LGTMです！
